apiVersion: 1

datasources:
  - name: Prometheus
    uid: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    jsonData:
      timeInterval: __GRAFANA_PROMETHEUS_TIME_INTERVAL__
    isDefault: true
    editable: true
